#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-re2j
Version  : e2j.1.1
Release  : 2
URL      : https://github.com/google/re2j/archive/re2j-1.1.tar.gz
Source0  : https://github.com/google/re2j/archive/re2j-1.1.tar.gz
Source1  : https://repo1.maven.org/maven2/com/google/re2j/re2j/1.1/re2j-1.1.jar
Source2  : https://repo1.maven.org/maven2/com/google/re2j/re2j/1.1/re2j-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-re2j-data = %{version}-%{release}

%description
RE2/J: linear time regular expression matching in Java
======================================================

%package data
Summary: data components for the mvn-re2j package.
Group: Data

%description data
data components for the mvn-re2j package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/re2j/re2j/1.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/google/re2j/re2j/1.1/re2j-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/google/re2j/re2j/1.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/google/re2j/re2j/1.1/re2j-1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/google/re2j/re2j/1.1/re2j-1.1.jar
/usr/share/java/.m2/repository/com/google/re2j/re2j/1.1/re2j-1.1.pom
